#- name: Setup SystemD Service file
#  ansible.builtin.template:
#    src: "{{component}}.service"
#    dest: /etc/systemd/system/{{component}}.service
#
#- name: Start {{ component }} service
#  ansible.builtin.systemd:
#    name: "{{ component }}"
#    state: restarted
#    enabled: true
#    daemon_reload: true
- name: Setup SystemD Service file
  ansible.builtin.template:
    src: "{{ component }}.service"
    dest: "/etc/systemd/system/{{ component }}.service"
  notify:
    - Reload systemd

- name: Start {{ component }} service
  ansible.builtin.systemd:
    name: "{{ component }}"
    state: restarted
    enabled: true
  when: ansible_facts['os_family'] == 'Linux'  # Only for Linux systems
  register: service_status
  ignore_errors: yes  # Optional, to avoid failure if the service is already running

- name: Debug service status
  ansible.builtin.debug:
    var: service_status
